ALTER TABLE public.patients
ADD COLUMN IF NOT EXISTS age INTEGER,
ADD COLUMN IF NOT EXISTS monitoring_status TEXT NOT NULL DEFAULT 'ACTIVE',
ADD COLUMN IF NOT EXISTS status_since TIMESTAMPTZ NOT NULL DEFAULT now(),
ADD COLUMN IF NOT EXISTS is_discharged BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS discharged_at TIMESTAMPTZ;

ALTER TABLE public.alerts
ADD COLUMN IF NOT EXISTS action TEXT;
